% vsaSentence (vowel-space centralization with sentences): run_vsaSentence_expt, test mode unless LR_FULL=1.
plan.name = 'vsaSentence';
plan.repos = {'vsaSentence'};
plan.exptDir = 'vsaSentence';
plan.entry = 'run_vsaSentence_expt';
plan.args = {struct('snum', 'lr001'), ~strcmp(getenv('LR_FULL'), '1')};
plan.gender = 'male';
% The sentence list lives on the lab server (hsList.xlsx, not in the repo). Stand-in: Harvard sentences (IEEE 1969,
% lists 1-2, public domain; each used twice) then 10 hVd/CVC words, matching the script's 40 'sentence' + 10 'word'
% labels, as a one-row (tab-separated) text file next to the expected path (read by the readcell compat).
hs = {'The birch canoe slid on the smooth planks.', 'Glue the sheet to the dark blue background.', 'It is easy to tell the depth of a well.', ...
  'These days a chicken leg is a rare dish.', 'Rice is often served in round bowls.', 'The juice of lemons makes fine punch.', ...
  'The box was thrown beside the parked truck.', 'The hogs were fed chopped corn and garbage.', 'Four hours of steady work faced us.', ...
  'A large size in stockings is hard to sell.', 'The boy was there when the sun rose.', 'A rod is used to catch pink salmon.', ...
  'The source of the huge river is the clear spring.', 'Kick the ball straight and follow through.', 'Help the woman get back to her feet.', ...
  'A pot of tea helps to pass the evening.', 'Smoky fires lack flame and heat.', 'The soft cushion broke the fall.', ...
  'The salt breeze came across from the sea.', 'The girl at the booth sold fifty bonds.'};
plan.pre = @() lr_plan_files({'\\wcs-cifs\wc\smng\experiments\vsaSentence\hsList.xlsx.labrun.txt', strjoin([repmat(hs, 1, 2), {'bead', 'bid', 'bed', 'bad', 'bod', 'bud', 'booed', 'bode', 'bayed', 'hood'}], "\t")}, ...
  @() lr_make_cbperm('\\wcs-cifs\wc\smng\experiments\vsaSentence\', 'vsaSentence', {'adapt', 'null'; 'adapt', 'null'}));
