#!/bin/bash
# Assemble the public GitHub Pages site for jmandel/audapter-report into <repo>/docs/,
# then run the public-information gate. Nothing is pushed by this script.
set -euo pipefail
A=$(cd "$(dirname "$0")/.." && pwd); S="$(cd "$A/.." && pwd)/docs"   # GitHub Pages serves /docs on main
rm -rf "$S"; mkdir -p "$S"
cp -r "$A/report/prototype/." "$S/"
touch "$S/.nojekyll"
cp "$A/../blab/audapter_mex/LICENSE" "$S/LICENSE-audapter-apache-2.0.txt"
cat > "$S/ATTRIBUTION.md" <<'MD'
# Attribution and provenance
This report analyses public open-source code only:
- blab-lab/audapter_mex @169cadffef4c2d82a33939b840245b8a8a9db0de (Apache-2.0)
- blab-lab/audapter_matlab @e1695f146a0ecc3014ffe34b2b3cbc578edcd4b2
- shanqing-cai/audapter_mex @f547196483fd2e68ef33f8a6fa7ed532eefd5af5 (Apache-2.0)
The WebAssembly builds in wasm/ are compiled from those sources (see LICENSE-audapter-apache-2.0.txt), plus the
patch files named in the report for the "patched" variants. Code excerpts are quoted from the same commits.
Audio: synthetic signals generated by the audit harness, processed by Audapter; the babble-noise excerpt is
mtbabble48k.wav from blab-lab/audapter_matlab.
MD
# ---- public-information gate ----
fail=0
chk() { if grep -rIl -i -E "$1" "$S" >/dev/null 2>&1; then echo "GATE FAIL ($2):"; grep -rIl -i -E "$1" "$S" | sed 's/^/  /'; fail=1; fi; }
# private-name check: patterns kept in an untracked local file (see later versions of this script)
chk '/home/[a-vx-z]|/home/w[a-df-z]|~/hobby|\.agent-scratch|jmandel/hobby' 'local filesystem paths (Emscripten /home/web_user is allowed)'
chk 'claude-(opus|sonnet|haiku|fable)|opus [0-9]|sonnet [0-9]' 'model identifiers'
chk 'gho_|ghp_|github_pat_|sk-ant-' 'tokens'
emails=$(grep -rIoh -E '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[a-z]{2,}' "$S" | grep -v -E '@(anthropic\.com)$' | sort -u || true)
[[ -n "$emails" ]] && { echo "GATE REVIEW (email addresses present):"; echo "$emails" | sed 's/^/  /'; }
big=$(find "$S" -type f -size +20M); [[ -n "$big" ]] && { echo "GATE FAIL (files >20MB): $big"; fail=1; }
echo "site: $(du -sh "$S" | cut -f1), $(find "$S" -type f | wc -l) files"
[[ $fail == 0 ]] && echo "GATE PASS" || { echo "GATE FAILED"; exit 1; }
