#!/bin/bash
# Assemble the public GitHub Pages site for jmandel/audapter-report into <repo>/docs/,
# then run the public-information gate. Nothing is pushed by this script.
set -euo pipefail
A=$(cd "$(dirname "$0")/.." && pwd); S="$(cd "$A/.." && pwd)/docs"   # GitHub Pages serves /docs on main
rm -rf "$S"; mkdir -p "$S"
cp -r "$A/report/prototype/." "$S/"
touch "$S/.nojekyll"
# Playground (audit/playground, built by its build.sh into dist/): published at docs/playground/ when present.
if [[ -d "$A/playground/dist" ]]; then mkdir -p "$S/playground"; cp -r "$A/playground/dist/." "$S/playground/"; else echo "note: audit/playground/dist not built; playground not staged"; fi
cp "$A/../blab/audapter_mex/LICENSE" "$S/LICENSE-audapter-apache-2.0.txt"
cp "$A/../LICENSE" "$S/LICENSE-apache-2.0.txt"; cp "$A/../LICENSE-CC-BY-4.0.txt" "$S/"; cp "$A/../NOTICE" "$S/NOTICE.txt"
cat > "$S/LICENSE.md" <<'MD'
# License
- Report text, figures and audio renderings: © 2026 Josh Mandel, [CC BY 4.0](LICENSE-CC-BY-4.0.txt).
- Code, including the WebAssembly builds of Audapter and the page scripts: [Apache-2.0](LICENSE-apache-2.0.txt). See [NOTICE](NOTICE.txt).
- Third-party sources and data: see [ATTRIBUTION.md](ATTRIBUTION.md).
MD
cat > "$S/ATTRIBUTION.md" <<'MD'
# Attribution and provenance
This report analyses public open-source code only:
- blab-lab/audapter_mex @169cadffef4c2d82a33939b840245b8a8a9db0de (Apache-2.0)
- blab-lab/audapter_matlab @e1695f146a0ecc3014ffe34b2b3cbc578edcd4b2
- shanqing-cai/audapter_mex @f547196483fd2e68ef33f8a6fa7ed532eefd5af5 (Apache-2.0)
The WebAssembly builds in wasm/ are compiled from those sources (see LICENSE-audapter-apache-2.0.txt), plus the
patch files named in the report for the "patched" variants. Code excerpts are quoted from the same commits.
Audio: synthetic signals generated by the audit harness, processed by Audapter; the babble-noise excerpt is
mtbabble48k.wav from blab-lab/audapter_matlab. Real-speech clips come from the audit's open corpus (audit/corpus), cut,
converted to mono 48 kHz and processed by Audapter (modified versions):
- CMU ARCTIC (Kominek & Black 2003), http://festvox.org/cmu_arctic/ - (c) 2003 Carnegie Mellon University, CMU ARCTIC
  licence; the full notice is in assets/licenses/CMU_ARCTIC_COPYING.txt
- LibriSpeech (Panayotov et al. 2015), https://www.openslr.org/12/ - CC BY 4.0
- speechocean762 (Zhang et al. 2021), https://www.openslr.org/101/ - CC BY 4.0
- VoiceBank-DEMAND noisy speech (Valentini-Botinhao 2017), doi:10.7488/ds/2117 - CC BY 4.0
- Perceptual Voice Qualities Database (Walden 2022), doi:10.17632/9dz247gnyb.4 - CC BY 4.0
- VocalSet (Wilkins et al. 2018), doi:10.5281/zenodo.1442513 - CC BY 4.0
- vocadito (Bittner et al. 2021), doi:10.5281/zenodo.5578807 - CC BY 4.0
- Audapter example trials (audapter_matlab example_data, MIT; audapter_mex mcode, Apache-2.0), (c) Audapter Authors
Hillenbrand et al. (1995) data were used for numbers only and are not distributed. Praat sample sounds were used in the
analysis only and are not distributed.
MD
# ---- public-information gate ----
fail=0
chk() { if grep -rIl -i -E "$1" "$S" >/dev/null 2>&1; then echo "GATE FAIL ($2):"; grep -rIl -i -E "$1" "$S" | sed 's/^/  /'; fail=1; fi; }
# Private repositories: links to them are never published. Their bare names are blocked too, except experiment names
# Josh approved for citation (listed in the untracked publish/private-allowed.local). Both lists are untracked, so the
# gate itself doesn't publish them.
PRIV="$A/publish/private-patterns.local"; ALLOW="$A/publish/private-allowed.local"
if [[ -s "$PRIV" ]]; then
  chk "github\.com/[^/ ]+/($(paste -sd'|' "$PRIV"))([^A-Za-z0-9_-]|$)" 'links to private repositories'
  BLOCK=$(grep -v -x -F -f <( [[ -s "$ALLOW" ]] && cat "$ALLOW" || echo '__none__') "$PRIV" | paste -sd'|')
  [[ -n "$BLOCK" ]] && chk "(^|[^A-Za-z0-9_-])($BLOCK)([^A-Za-z0-9_-]|$)" 'private names not approved for citation (publish/private-allowed.local)'
else echo "note: no publish/private-patterns.local; private-name check skipped"; fi
chk '/home/[a-vx-z]|/home/w[a-df-z]|~/hobby|\.agent-scratch|jmandel/hobby' 'local filesystem paths (Emscripten /home/web_user is allowed)'
chk 'claude-(opus|sonnet|haiku|fable)|opus [0-9]|sonnet [0-9]' 'model identifiers'
chk 'gho_|ghp_|github_pat_|sk-ant-' 'tokens'
emails=$(grep -rIoh -E '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[a-z]{2,}' "$S" | grep -v -E '@(anthropic\.com)$' | sort -u || true)
[[ -n "$emails" ]] && { echo "GATE REVIEW (email addresses present):"; echo "$emails" | sed 's/^/  /'; }
big=$(find "$S" -type f -size +20M); [[ -n "$big" ]] && { echo "GATE FAIL (files >20MB): $big"; fail=1; }
echo "site: $(du -sh "$S" | cut -f1), $(find "$S" -type f | wc -l) files"
[[ $fail == 0 ]] && echo "GATE PASS" || { echo "GATE FAILED"; exit 1; }
